# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Username')),
                ('firstname', models.CharField(max_length=15, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=15, verbose_name='Last Name')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
            ],
        ),
    ]
