# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=15, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=15, verbose_name='Last Name')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('access', models.CharField(max_length=10, verbose_name='Access Level')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
