stages:
  - deploy

variables:


IDK:
  stage: deploy

  tags:
    - test


  environment:
    name: Test
    url:

  script:
    - sudo docker-compose build --no-cache && sudo docker-compose up -d





