version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ncart_work-ng01
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: ncart_work-web
    command: bash -c "python ncart_work/manage.py makemigrations && python ncart_work/manage.py migrate && gunicorn ncart_work.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./ncart_work:/src

    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ncart_work-ps01
