version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: 3cx-ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: 3cx-web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn Work_manager.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./:/src
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: 3cx-ps01