# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30, verbose_name='Client')),
                ('streetaddress', models.CharField(max_length=300, verbose_name='Street Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('zip', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('date', models.DateField(verbose_name='Date Performed')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
            ],
        ),
    ]
