# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncart_app', '0002_firewall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Port Number')),
                ('transport', models.CharField(max_length=4, verbose_name='TCP/UDP')),
                ('source', models.CharField(max_length=12, verbose_name='Source')),
                ('destination', models.CharField(max_length=12, verbose_name='Destination')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('firewall', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncart_app.Project', verbose_name='Firewall Name')),
            ],
        ),
    ]
