# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncart_app', '0004_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
