# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncart_app', '0005_firewall_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
